<!-- wp:group {"className":"brandy-halloween-v2-product-group","style":{"spacing":{"blockGap":"0"},"border":{"radius":"20px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group brandy-halloween-v2-product-group" style="border-radius:20px"><!-- wp:woocommerce/product-image {"saleBadgeAlign":"left","isDescendentOfQueryLoop":true,"height":"","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"20px"}}} /-->

<!-- wp:group {"className":"brandy-halloween-v2-product-content","style":{"spacing":{"blockGap":"0","padding":{"top":"30px","bottom":"20px","left":"20px","right":"var:preset|spacing|40"}},"dimensions":{"minHeight":"0px"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group brandy-halloween-v2-product-content" style="min-height:0px;padding-top:30px;padding-right:var(--wp--preset--spacing--40);padding-bottom:20px;padding-left:20px"><!-- wp:post-title {"textAlign":"left","level":3,"isLink":true,"className":"brandy-link-underline-to-child","style":{"spacing":{"margin":{"bottom":"5px","top":"0"}},"typography":{"fontStyle":"normal","fontWeight":"400"}},"fontSize":"base","fontFamily":"lexend","__woocommerceNamespace":"woocommerce/product-collection/product-title"} /-->

<!-- wp:woocommerce/product-price {"isDescendentOfQueryLoop":true,"textAlign":"left","fontSize":"base","style":{"spacing":{"margin":{"top":"0"}},"typography":{"fontStyle":"normal","fontWeight":"500"}},"originalPriceTypography":{"fontSize":"","color":"","appearance":{"key":"regular","name":"Regular","style":{"fontStyle":"normal","fontWeight":"400"}}}} /--></div>
<!-- /wp:group -->

<!-- wp:group {"className":"brandy-halloween-v2-product-actions","style":{"spacing":{"padding":{"right":"var:preset|spacing|20","bottom":"var:preset|spacing|10"},"blockGap":"12px"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"bottom"}} -->
<div class="wp-block-group brandy-halloween-v2-product-actions" style="padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--10)"><!-- wp:woocommerce/product-button {"isDescendentOfQueryLoop":true,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"100%"},"color":{"text":"#000000","background":"#e0e3ec"},"elements":{"link":{"color":{"text":"#000000"}}}},"hoverBackgroundColor":"#E26B0F","hoverTextColor":"#ffffff"} /-->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"12px","bottom":"12px","left":"12px","right":"12px"}},"border":{"radius":"50px"},"color":{"background":"#e0e3ec"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="border-radius:50px;background-color:#e0e3ec;padding-top:12px;padding-right:12px;padding-bottom:12px;padding-left:12px"><!-- wp:image {"width":"20px","height":"20px","scale":"contain","sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://images.wpbrandy.com/uploads/view-icon.png" alt="" style="object-fit:contain;width:20px;height:20px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:brandy/add-to-wishlist {"icon":"https://images.wpbrandy.com/uploads/plants-wishlist-icon.png","iconHover":"https://images.wpbrandy.com/uploads/plants-wishlist-icon-hover.png","iconActive":"https://images.wpbrandy.com/uploads/wishlist-yellow-icon.png","iconSize":"18px","backgroundColor":"#e0e3ec","backgroundColorHover":"#E26B0F","backgroundColorActive":"#ffffff","defaultText":"","addedText":"","className":"has-ffffff-background-color has-background","style":{"spacing":{"padding":{"top":"13px","bottom":"13px","left":"13px","right":"13px"}},"border":{"radius":"100%"}}} -->
<div data-product-id="" style="border-radius:100%;padding-top:13px;padding-right:13px;padding-bottom:13px;padding-left:13px;--atw-background-color:#e0e3ec;--atw-background-color-hover:#E26B0F;--atw-background-color-active:#ffffff;--atw-text-color:;--atw-text-color-hover:;--atw-text-color-active:;--atw-icon-size:18px;--atw-loading-spinner-color:#000000" class="wp-block-brandy-add-to-wishlist has-ffffff-background-color has-background"><span class="wp-block-brandy-add-to-wishlist-loading"></span><div class="wp-block-brandy-add-to-wishlist-icon-wrap"><img src="https://images.wpbrandy.com/uploads/plants-wishlist-icon.png" class="wp-block-brandy-add-to-wishlist-icon default-state" alt="add-to-wishlist-icon"/><img src="https://images.wpbrandy.com/uploads/plants-wishlist-icon-hover.png" class="wp-block-brandy-add-to-wishlist-icon hover-state" alt="add-to-wishlist-icon-hover"/><img src="https://images.wpbrandy.com/uploads/wishlist-yellow-icon.png" class="wp-block-brandy-add-to-wishlist-icon active-state" alt="add-to-wishlist-icon-active"/></div></div>
<!-- /wp:brandy/add-to-wishlist --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->