<!-- wp:group {"className":"brandy-houseware-product-template__thumbnail-group","style":{"border":{"radius":"18px"},"spacing":{"blockGap":"0","margin":{"bottom":"22px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group brandy-houseware-product-template__thumbnail-group" style="border-radius:18px;margin-bottom:22px"><!-- wp:woocommerce/product-image {"saleBadgeAlign":"left","imageSizing":"thumbnail","isDescendentOfQueryLoop":true,"style":{"spacing":{"margin":{"top":"0","bottom":"0"}},"border":{"radius":"18px"}}} /-->

<!-- wp:woocommerce/product-button {"textAlign":"left","width":100,"isDescendentOfQueryLoop":true,"fontSize":"small","style":{"spacing":{"margin":{"bottom":"0","left":"0","right":"0"}},"typography":{"fontStyle":"normal","fontWeight":"600"}}} /-->

<!-- wp:brandy/add-to-wishlist {"icon":"https://images.wpbrandy.com/uploads/20240912044751/wishlist-icon.png","iconHover":"https://images.wpbrandy.com/uploads/20240912044751/wishlist-icon.png","iconActive":"https://images.wpbrandy.com/uploads/houseware-wishlist-icon-active.png","defaultText":"","addedText":""} -->
<div data-product-id="" style="--atw-background-color:#ffffff00;--atw-background-color-hover:#ffffff00;--atw-background-color-active:#ffffff00;--atw-text-color:;--atw-text-color-hover:;--atw-text-color-active:;--atw-icon-size:20px;--atw-loading-spinner-color:#000000" class="wp-block-brandy-add-to-wishlist"><span class="wp-block-brandy-add-to-wishlist-loading"></span><div class="wp-block-brandy-add-to-wishlist-icon-wrap"><img src="https://images.wpbrandy.com/uploads/20240912044751/wishlist-icon.png" class="wp-block-brandy-add-to-wishlist-icon default-state" alt="add-to-wishlist-icon"/><img src="https://images.wpbrandy.com/uploads/20240912044751/wishlist-icon.png" class="wp-block-brandy-add-to-wishlist-icon hover-state" alt="add-to-wishlist-icon-hover"/><img src="https://images.wpbrandy.com/uploads/houseware-wishlist-icon-active.png" class="wp-block-brandy-add-to-wishlist-icon active-state" alt="add-to-wishlist-icon-active"/></div></div>
<!-- /wp:brandy/add-to-wishlist --></div>
<!-- /wp:group -->

<!-- wp:post-title {"textAlign":"left","level":3,"isLink":true,"className":"brandy-link-underline-to-child","style":{"spacing":{"margin":{"bottom":"6px","top":"0"}},"typography":{"fontStyle":"normal","fontWeight":"400"}},"fontSize":"base","__woocommerceNamespace":"woocommerce/product-collection/product-title"} /-->

<!-- wp:woocommerce/product-price {"isDescendentOfQueryLoop":true,"textAlign":"left","style":{"spacing":{"margin":{"top":"0"}},"typography":{"fontStyle":"normal","fontWeight":"500","fontSize":"20px"}},"originalPriceTypography":{"fontSize":"0.875rem","color":"","appearance":{"key":"regular","name":"Regular","style":{"fontStyle":"normal","fontWeight":"400"}}}} /-->